"""procesos fase 3: step_links y step_metrics

Revision ID: 3bb08d08b5b6
Revises: c2a8a726cd17
Create Date: 2026-07-02 09:45:34.852950
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '3bb08d08b5b6'
down_revision: Union[str, None] = 'c2a8a726cd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_links',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['process_steps.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_links_step_id'), ['step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_links_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('step_metrics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hours_per_cycle', sa.Float(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_per_cycle', sa.Float(), nullable=False),
    sa.Column('cycle_time_hours', sa.Float(), nullable=False),
    sa.Column('errors', sa.Float(), nullable=False),
    sa.Column('volume_month', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['process_steps.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_metrics_step_id'), ['step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_metrics_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_metrics_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_step_metrics_step_id'))

    op.drop_table('step_metrics')
    with op.batch_alter_table('step_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_links_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_step_links_step_id'))

    op.drop_table('step_links')
    # ### end Alembic commands ###
