"""procesos de negocio: lineas/servicios/procesos/pasos

Revision ID: c2a8a726cd17
Revises: f42c660d82f9
Create Date: 2026-07-02 09:05:09.631571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c2a8a726cd17'
down_revision: Union[str, None] = 'f42c660d82f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_lines',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_lines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('business_services',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sla_ola', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['business_lines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_services_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('business_processes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['business_services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_processes_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_processes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('service_clients',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['business_services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_clients_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_clients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('process_steps',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('automation_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['business_processes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_process_steps_process_id'), ['process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_process_steps_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_process_steps_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_process_steps_process_id'))

    op.drop_table('process_steps')
    with op.batch_alter_table('service_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_clients_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_service_clients_service_id'))

    op.drop_table('service_clients')
    with op.batch_alter_table('business_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_processes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_business_processes_service_id'))

    op.drop_table('business_processes')
    with op.batch_alter_table('business_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_services_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_business_services_line_id'))

    op.drop_table('business_services')
    with op.batch_alter_table('business_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_lines_tenant_id'))

    op.drop_table('business_lines')
    # ### end Alembic commands ###
