"""baseline: esquema inicial

Revision ID: f42c660d82f9
Revises: 
Create Date: 2026-07-02 08:11:26.693647
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'f42c660d82f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('provider_settings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_settings_route'), ['route'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kms_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('allows_external', sa.Boolean(), nullable=False),
    sa.Column('allows_vpc', sa.Boolean(), nullable=False),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_from_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seats_licensed', sa.Integer(), nullable=False),
    sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_renews_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('annual_fee_mxn', sa.Integer(), nullable=False),
    sa.Column('n8n_webhook_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n8n_api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n8n_auth_header', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n8n_provisioned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tools', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privacy_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requires_premium_reasoning', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_models', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivity'), nullable=True),
    sa.Column('selected_route', sa.Enum('LOCAL', 'VPC', 'OPEN', 'PREMIUM', 'BLOCKED', name='modelroute'), nullable=True),
    sa.Column('selected_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('catalog_recipes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inputs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('produces', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_recipes_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_recipes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('company_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gov_tramites', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audience', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_prop', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goals', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('areas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('connectors',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_header', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connectors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dsn_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('document_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('finance_datasets',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('finetune_datasets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finetune_datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finetune_datasets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('known_errors',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symptom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('known_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_known_errors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('n8n_recipes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('n8n_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_n8n_recipes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('odata_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('odata_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('select', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odata_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odata_sources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sftp_connectors',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remote_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sftp_connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sftp_connectors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sharepoint_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sharepoint_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sharepoint_sources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_tramites',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('municipio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requisitos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pasos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('costo_aprox', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fuente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_tramites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_tramites_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', 'SECURITY', 'DEVOPS', name='role'), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mfa_backup_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callmebot_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callmebot_apikey_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('action_grants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_grants_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_grants_user_id'), ['user_id'], unique=False)

    op.create_table('action_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_requests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_requests_user_id'), ['user_id'], unique=False)

    op.create_table('agent_playbooks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_playbooks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_playbooks_user_id'), ['user_id'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channels', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_digest_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_user_id'), ['user_id'], unique=False)

    op.create_table('app_projects',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('deploy_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('automations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_run', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('connections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('dashboards',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sensitivity', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivity'), nullable=False),
    sa.Column('pii_score', sa.Float(), nullable=False),
    sa.Column('pii_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('finetune_examples',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['finetune_datasets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finetune_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finetune_examples_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finetune_examples_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('finetune_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adapter_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serve_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['finetune_datasets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finetune_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finetune_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('generated_images',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_b64', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_images_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mail_digest_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channels', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discard_propaganda', sa.Boolean(), nullable=False),
    sa.Column('pending_enabled', sa.Boolean(), nullable=False),
    sa.Column('pending_days', sa.Integer(), nullable=False),
    sa.Column('sender_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_run_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_digest_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_digest_configs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_digest_configs_user_id'), ['user_id'], unique=False)

    op.create_table('memory_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_items_user_id'), ['user_id'], unique=False)

    op.create_table('notebooks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notebooks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notebooks_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('recipe_proposals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_proposals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('recipe_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inputs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_runs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('spaces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modules', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaces_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sensitivity', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivity'), nullable=False),
    sa.Column('embedding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_redacted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sa.Enum('LOCAL', 'VPC', 'OPEN', 'PREMIUM', 'BLOCKED', name='modelroute'), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaces_tenant_id'))

    op.drop_table('spaces')
    with op.batch_alter_table('recipe_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_runs_tenant_id'))

    op.drop_table('recipe_runs')
    with op.batch_alter_table('recipe_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_proposals_tenant_id'))

    op.drop_table('recipe_proposals')
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_tenant_id'))

    op.drop_table('oauth_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_tenant_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notebooks_user_id'))
        batch_op.drop_index(batch_op.f('ix_notebooks_tenant_id'))

    op.drop_table('notebooks')
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_memory_items_tenant_id'))

    op.drop_table('memory_items')
    with op.batch_alter_table('mail_digest_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_digest_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_mail_digest_configs_tenant_id'))

    op.drop_table('mail_digest_configs')
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_images_tenant_id'))

    op.drop_table('generated_images')
    with op.batch_alter_table('finetune_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finetune_jobs_tenant_id'))

    op.drop_table('finetune_jobs')
    with op.batch_alter_table('finetune_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finetune_examples_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_finetune_examples_dataset_id'))

    op.drop_table('finetune_examples')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_tenant_id'))

    op.drop_table('documents')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_tenant_id'))

    op.drop_table('dashboards')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_tenant_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_tenant_id'))

    op.drop_table('connections')
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automations_tenant_id'))

    op.drop_table('automations')
    with op.batch_alter_table('app_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_projects_tenant_id'))

    op.drop_table('app_projects')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_tenant_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('agent_playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_playbooks_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_playbooks_tenant_id'))

    op.drop_table('agent_playbooks')
    with op.batch_alter_table('action_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_requests_tenant_id'))

    op.drop_table('action_requests')
    with op.batch_alter_table('action_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_grants_tenant_id'))

    op.drop_table('action_grants')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_tenant_id'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tenant_tramites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_tramites_tenant_id'))

    op.drop_table('tenant_tramites')
    with op.batch_alter_table('sharepoint_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sharepoint_sources_tenant_id'))

    op.drop_table('sharepoint_sources')
    with op.batch_alter_table('sftp_connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sftp_connectors_tenant_id'))

    op.drop_table('sftp_connectors')
    with op.batch_alter_table('odata_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odata_sources_tenant_id'))

    op.drop_table('odata_sources')
    with op.batch_alter_table('n8n_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_n8n_recipes_tenant_id'))

    op.drop_table('n8n_recipes')
    with op.batch_alter_table('known_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_known_errors_tenant_id'))

    op.drop_table('known_errors')
    with op.batch_alter_table('finetune_datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finetune_datasets_tenant_id'))

    op.drop_table('finetune_datasets')
    op.drop_table('finance_datasets')
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_categories_tenant_id'))

    op.drop_table('document_categories')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_tenant_id'))

    op.drop_table('data_sources')
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connectors_tenant_id'))

    op.drop_table('connectors')
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_profiles_tenant_id'))

    op.drop_table('company_profiles')
    with op.batch_alter_table('catalog_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_recipes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_catalog_recipes_slug'))

    op.drop_table('catalog_recipes')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_tenant_id'))

    op.drop_table('agents')
    op.drop_table('tenants')
    with op.batch_alter_table('provider_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_settings_route'))

    op.drop_table('provider_settings')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
